export const courseTemplate = [
    {
        major: "计算机科学与技术",
        requiredCredits: 109,
        numerical_logic_credits: 3,
        coreCourses: 13, 
        limitedElectives: 4,  
        elective_credits: 9, 
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 161
    },
    {
        major: "物联网工程",
        requiredCredits: 109,
        numerical_logic_credits: 3,
        coreCourses: 13,
        limitedElectives: 4,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 161
    },
    {
        major: "人工智能",
        requiredCredits: 109,
        numerical_logic_credits: 3,
        coreCourses: 13,
        limitedElectives: 4,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 161
    },
    {
        major: "数据科学与大数据技术",
        requiredCredits: 109,
        numerical_logic_credits: 3,
        coreCourses: 13,
        limitedElectives: 4,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 161
    },
    {
        major: "生物信息学",
        requiredCredits: 109,
        numerical_logic_credits: 3,
        coreCourses: 13,
        limitedElectives: 4,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 161
    },
    {
        major: "网络空间安全",
        requiredCredits: 108,
        numerical_logic_credits: 3,
        coreCourses: 13,
        limitedElectives: 4,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 160
    },
    {
        major: "信息安全",
        requiredCredits: 108,
        numerical_logic_credits: 3,
        coreCourses: 13,
        limitedElectives: 4,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 160
    },
    {
        major: "软件工程",
        requiredCredits: 109,
        numerical_logic_credits: 0,
        coreCourses: 14,
        limitedElectives: 7,
        elective_credits: 9,
        international_credits: 1,
        short_term_training_credits: 2,
        outmajor_credits: 6,
        culture_core_credits: 4,
        culture_choose_credits: 5,
        lectureQuality: 1,
        innovation_credits: 4,
        total: 162
    }
];
